#!/usr/bin/env python3
"""
Generate a packed, first-reading-only pinyin lookup dataset for the PHP loader
(php/src/PinyinData.php) from pinyin.txt and tone_removal.txt.

Unlike pinyin.txt (an OpenCC text dictionary carrying every reading), the packed
dataset is optimized for O(1) codepoint-addressed lookup:

- dist/php/syllables.php  PHP array of distinct tone-marked syllables (the value
                          table). Indexes into this table are what the binary
                          strips store.
- dist/php/tone_map.php   PHP map of tone-marked letter => base letter, so the
                          loader can strip tones at runtime when a caller asks
                          for toneless output (ü stays ü).
- dist/php/bmp.bin        One uint16 little-endian syllable index per codepoint
                          for U+3400..U+9FFF (CJK Ext A + URO). 0xFFFF = no
                          reading.
- dist/php/supp.bin       Same encoding for U+20000..U+2EBEF (CJK Ext B..F).
- dist/php/extra.php      PHP array for the handful of entries outside both
                          strips (compatibility ideographs, Kangxi radicals,
                          U+3007).
- dist/php/meta.php       Strip definitions (file, lo, hi) so the PHP loader
                          stays range-agnostic.

Only the FIRST reading of each character is kept, WITH tone marks. Toneless
output is produced on the loader side via tone_map.php, so the binary strips
(the bulk of the dataset) are unchanged from the toneless layout: their size
depends only on the codepoint ranges, not on whether syllables carry tones.
The dataset is complete and policy-free: every character in pinyin.txt is
included. Consumers with input policies (e.g. script or variant restrictions)
should enforce them on their own side rather than filtering this data.

Usage:
    python3 gen_packed_dict.py [pinyin.txt] [dist/php]
"""

import argparse
import struct
import sys
from pathlib import Path

STRIPS = [
    ('bmp.bin', 0x3400, 0x9FFF),
    ('supp.bin', 0x20000, 0x2EBEF),
]
NO_READING = 0xFFFF


def load_tone_removal(path: Path) -> dict[str, str]:
    mapping: dict[str, str] = {}
    for line in path.read_text(encoding='utf-8').splitlines():
        if not line.strip():
            continue
        marked, base = line.split('\t')
        mapping[marked] = base
    return mapping


def load_entries(pinyin_path: Path, tone_map: dict[str, str]) -> dict[int, str]:
    entries: dict[int, str] = {}
    for line in pinyin_path.read_text(encoding='utf-8').splitlines():
        if '\t' not in line:
            continue
        char, readings = line.split('\t', 1)
        if len(char) != 1:
            raise SystemExit(f'unexpected multi-codepoint key: {char!r}')
        first = readings.split(' ')[0]
        # Keep tone marks, but require that every non-ASCII letter can either
        # stay (bare ü) or be stripped to ASCII via tone_map, so the loader can
        # always produce clean toneless output.
        if not all(ch.isascii() or ch == 'ü' or ch in tone_map for ch in first):
            raise SystemExit(
                f'{char}: letter in {first!r} not covered by tone_removal.txt'
            )
        entries[ord(char)] = first
    return entries


def php_quote(value: str) -> str:
    return "'" + value.replace('\\', '\\\\').replace("'", "\\'") + "'"


def write_php_array(path: Path, header: str, body_lines: list[str]) -> None:
    lines = ['<?php', '', f'// {header}', '// Generated by gen_packed_dict.py. Do not edit by hand.', '']
    lines.append('return [')
    lines.extend(body_lines)
    lines.append('];')
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('pinyin', nargs='?', default='pinyin.txt', type=Path)
    parser.add_argument('outdir', nargs='?', default=Path('dist/php'), type=Path)
    args = parser.parse_args()

    tone_map = load_tone_removal(Path('tone_removal.txt'))
    entries = load_entries(args.pinyin, tone_map)

    syllables = sorted({p for p in entries.values()})
    if len(syllables) >= NO_READING:
        raise SystemExit('syllable table exceeds uint16 sentinel capacity')
    syll_index = {s: i for i, s in enumerate(syllables)}

    args.outdir.mkdir(parents=True, exist_ok=True)

    write_php_array(
        args.outdir / 'syllables.php',
        'Tone-marked syllable value table; binary strips store indexes into it.',
        [f'    {php_quote(s)},' for s in syllables],
    )

    write_php_array(
        args.outdir / 'tone_map.php',
        'Tone-marked letter => base letter, for toneless output at runtime.',
        [f'    {php_quote(m)} => {php_quote(b)},' for m, b in sorted(tone_map.items())],
    )

    in_strip: set[int] = set()
    for filename, lo, hi in STRIPS:
        buf = bytearray()
        for cp in range(lo, hi + 1):
            idx = syll_index[entries[cp]] if cp in entries else NO_READING
            buf += struct.pack('<H', idx)
            if cp in entries:
                in_strip.add(cp)
        (args.outdir / filename).write_bytes(bytes(buf))

    extras = {cp: py for cp, py in sorted(entries.items()) if cp not in in_strip}
    write_php_array(
        args.outdir / 'extra.php',
        'Entries outside the binary strips (char => tone-marked pinyin).',
        [f'    {php_quote(chr(cp))} => {php_quote(py)},' for cp, py in extras.items()],
    )

    write_php_array(
        args.outdir / 'meta.php',
        'Binary strip layout: [file, first codepoint, last codepoint].',
        [f"    ['{f}', 0x{lo:X}, 0x{hi:X}]," for f, lo, hi in STRIPS],
    )

    total_bytes = sum((args.outdir / f).stat().st_size for f, _, _ in STRIPS)
    print(f'entries: {len(entries)}')
    print(f'syllables: {len(syllables)}')
    print(f'in strips: {len(in_strip)}, in extra.php: {len(extras)}')
    print(f'strip bytes: {total_bytes}')


if __name__ == '__main__':
    main()
