<?php

namespace OpenccPinyin;

/**
 * O(1) codepoint-addressed lookup over the packed toneless pinyin dataset
 * generated by gen_packed_dict.py (dist/php/).
 *
 * Data layout: a value table of distinct tone-marked syllables (syllables.php)
 * plus one uint16 little-endian index per codepoint in each binary strip
 * (bmp.bin, supp.bin; 0xFFFF = no reading). The few entries outside the
 * strips live in extra.php. Strip ranges come from meta.php so this class
 * needs no updating when strips change. tone_map.php maps each tone-marked
 * letter to its base letter for toneless output.
 *
 * Only the first reading of each character is stored, with tone marks. Pass
 * $tone = false to any accessor to get the toneless form (ü kept as ü),
 * stripped at runtime via tone_map.php. No polyphone disambiguation is
 * attempted; consumers that need curated readings register a char => reading
 * map via setOverrides(), which wins over the packed data.
 */
final class PinyinData {
    private const NO_READING = 0xFFFF;

    /** @var list<string>|null */
    private static ?array $syllables = null;

    /** @var array<string,string> */
    private static array $extra = [];

    /** @var array<string,string> tone-marked letter => base letter */
    private static array $toneMap = [];

    /** @var array<string,string> caller overrides, char => reading */
    private static array $overrides = [];

    /** @var list<array{string,int,int}> strip blobs as [blob, lo, hi] */
    private static array $strips = [];

    /**
     * Register caller overrides (char => reading) that win over the packed
     * dataset. The packed data keeps only each character's first reading, so
     * this is how consumers pin the correct reading for a polyphone in their
     * domain, or supply a reading for a character the dataset lacks.
     *
     * Provide readings tone-marked (matching the dataset convention); toneless
     * requests strip them through the same tone map. Replaces any previously
     * registered overrides; pass [] to clear.
     *
     * @param array<string,string> $overrides
     */
    public static function setOverrides(array $overrides): void {
        self::$overrides = $overrides;
    }

    /**
     * First reading for a single character, or null if neither the overrides
     * nor the packed dataset have one. Tone-marked by default; pass
     * $tone = false for the toneless form. Overrides win over packed data.
     */
    public static function lookup(string $char, bool $tone = true): ?string {
        self::ensureLoaded();

        $reading = self::$overrides[$char] ?? null;
        if ($reading === null) {
            if ($char === '') {
                return null;
            }
            $cp = mb_ord($char, 'UTF-8');
            if ($cp === false) {
                return null;
            }
            foreach (self::$strips as [$blob, $lo, $hi]) {
                if ($cp < $lo || $cp > $hi) {
                    continue;
                }
                $off = ($cp - $lo) * 2;
                $idx = ord($blob[$off]) | (ord($blob[$off + 1]) << 8);
                $reading = $idx === self::NO_READING ? null : self::$syllables[$idx];
                break;
            }
            $reading ??= self::$extra[$char] ?? null;
        }

        if ($reading === null || $tone) {
            return $reading;
        }

        return strtr($reading, self::$toneMap);
    }

    /**
     * Per-character syllable breakdown, preserving boundaries so callers can
     * choose their own joining rules (spaces, apostrophes, capitalization).
     *
     * @return list<array{char:string,pinyin:?string}> pinyin is null for
     *                                                 characters without a reading (incl. non-Han input).
     */
    public static function syllables(string $text, bool $tone = true): array {
        $out = [];
        foreach (preg_split('//u', $text, -1, PREG_SPLIT_NO_EMPTY) ?: [] as $char) {
            $out[] = ['char' => $char, 'pinyin' => self::lookup($char, $tone)];
        }

        return $out;
    }

    /**
     * Convenience join: syllables concatenated with $separator (default none),
     * characters without a reading kept as-is (preserving the "no reading"
     * signal for callers that validate output). Pass ' ' for space-separated
     * pinyin.
     */
    public static function toPinyin(string $text, string $separator = '', bool $tone = true): string {
        $parts = [];
        foreach (self::syllables($text, $tone) as $syllable) {
            $parts[] = $syllable['pinyin'] ?? $syllable['char'];
        }

        return implode($separator, $parts);
    }

    /**
     * Reset loaded data (for tests).
     */
    public static function reset(): void {
        self::$syllables = null;
        self::$extra = [];
        self::$toneMap = [];
        self::$overrides = [];
        self::$strips = [];
    }

    private static function ensureLoaded(): void {
        if (self::$syllables !== null) {
            return;
        }

        $dir = dirname(__DIR__, 2).'/dist/php';

        self::$syllables = require $dir.'/syllables.php';
        self::$extra = require $dir.'/extra.php';
        self::$toneMap = require $dir.'/tone_map.php';

        self::$strips = [];
        foreach (require $dir.'/meta.php' as [$file, $lo, $hi]) {
            $blob = file_get_contents($dir.'/'.$file);
            if ($blob === false || strlen($blob) !== ($hi - $lo + 1) * 2) {
                throw new \RuntimeException("packed pinyin strip {$file} is missing or truncated");
            }
            self::$strips[] = [$blob, $lo, $hi];
        }
    }
}
